---

# handlers file for mongodb

- name: restart mongod
  service: name=mongod state=restarted

- name: start mongod
  service: name=mongod state=started

- name: restart disable-thp
  service: name='disable-thp' state=restarted

- name: start disable-thp
  service: name='disable-thp' state=started
